main-font: &main-font Roboto Mono Nerd Font:style=solid:pixelsize=15

bar:
  height: 30
  location: top
  spacing: 5
  margin: 0

  font: *main-font

  foreground: ffffffff
  background: 111111ff

  left:
    - river:
        title:
          - string:
              text: "{mode}"
              margin: 10
              deco:
                background: { color: b54427ff }
          - map:
              conditions:
                title != "":
                  string:
                    text: "{title}"
                    max: 40
                    margin: 10
                    deco:
                      background: { color: 27687fff }
        content:
          map:
            conditions:
              focused:
                string:
                  margin: 10
                  text: "{id}"
                  deco:
                    background: {color: 333333ff}
              ~occupied: {empty: {}}
              occupied:
                string:
                  margin: 10
                  text: "{id}"
  
  center:
    - clock:
        time-format: "%H:%M:%S"
        content:
          string: {text: "{time}    {date}"}

  right:
    # - network:
    #     content:
    #       string: { text: "{name}: {state}", margin: 5 }
    - backlight:
        name: intel_backlight
        content:
          string: { text: " {percent}%" }
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{cubic_volume}%", foreground: ff0000ff}}
              ~muted: {string: {text: "{cubic_volume}%"}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluethoot":
                            string: {text: "  "}
                        default:
                          - ramp:
                              tag: cubic_volume
                              items:
                                - string: {text: "  "}
                                - string: {text: "  "}
                                - string: {text: "  "}
                    type == "source":
                      - string:
                          text: "  "
                          left-margin: 10
              - map:
                  <<: *volume
    - battery:
        name: BAT1
        poll-interval: 60000
        content:
          map:
            default:
                string:
                  text: "{state}  {capacity}%  {estimate}"
                  margin: 10
                  deco:
                    background: { color: b29e2aff }
            conditions:
              capacity > 70:
                string:
                  text: "{state}  {capacity}%  {estimate}"
                  margin: 10
                  deco:
                    background: { color: 34a339ff }
              capacity < 30:
                string:
                  text: "{state}  {capacity}%  {estimate}"
                  margin: 10
                  deco:
                    background: { color: a33734ff }
