[general]
import = [
    "${XDG_CONFIG_HOME}/alacritty/themes/themes/kanagawa_wave.toml"
]

[window]
decorations = "None"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 13
